name: Get News

on:
  schedule:    
    - cron: "0 4,16 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install -r requirements.txt

    - name: pull news
      run: python getnews.py

    - name: push
      run: |
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git add *
        git commit -m "sync"
        git push
