name: Get News

on:
  schedule:    
    - cron: "0 4,16 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set variables
        run: echo "DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Pull news
        run: python getnews.py

      - name: Push
        continue-on-error: true
        run: |
          git config --local user.name "actions"
          git config --local user.email "action@github.com"
          git add *
          git commit -m "${{ env.DATE }}"
          git push
